//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outliner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutlinerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutlinerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outliner.Resources.OutlinerResources", typeof(OutlinerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap activelayer {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "activelayer");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_button {
            get {
                return EmbeddedBitmapResources.Load("node_buttons", "add_button");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_button_disabled {
            get {
                return EmbeddedBitmapResources.Load("node_buttons", "add_button_disabled");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap advrename {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "advrename");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boxmode_button {
            get {
                return EmbeddedBitmapResources.Load("node_buttons", "boxmode_button");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boxmode_button_disabled {
            get {
                return EmbeddedBitmapResources.Load("node_buttons", "boxmode_button_disabled");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap childnodes {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "childnodes");
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selection To.
        /// </summary>
        internal static string ContextMenuAddTo {
            get {
                return ResourceManager.GetString("ContextMenuAddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Rename.
        /// </summary>
        internal static string ContextMenuAdvRename {
            get {
                return ResourceManager.GetString("ContextMenuAdvRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backface Cull.
        /// </summary>
        internal static string ContextMenuBackfaceCull {
            get {
                return ResourceManager.GetString("ContextMenuBackfaceCull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display As Box.
        /// </summary>
        internal static string ContextMenuBoxMode {
            get {
                return ResourceManager.GetString("ContextMenuBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Layer.
        /// </summary>
        internal static string ContextMenuCreateNewLayer {
            get {
                return ResourceManager.GetString("ContextMenuCreateNewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounding Box.
        /// </summary>
        internal static string ContextMenuDisplayBoundingBox {
            get {
                return ResourceManager.GetString("ContextMenuDisplayBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        internal static string ContextMenuDisplayProperties {
            get {
                return ResourceManager.GetString("ContextMenuDisplayProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Through.
        /// </summary>
        internal static string ContextMenuDisplaySeeThrough {
            get {
                return ResourceManager.GetString("ContextMenuDisplaySeeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaded.
        /// </summary>
        internal static string ContextMenuDisplayShaded {
            get {
                return ResourceManager.GetString("ContextMenuDisplayShaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajectory.
        /// </summary>
        internal static string ContextMenuDisplayTrajectory {
            get {
                return ResourceManager.GetString("ContextMenuDisplayTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewport.
        /// </summary>
        internal static string ContextMenuDisplayViewport {
            get {
                return ResourceManager.GetString("ContextMenuDisplayViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe.
        /// </summary>
        internal static string ContextMenuDisplayWireframe {
            get {
                return ResourceManager.GetString("ContextMenuDisplayWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit material in slot.
        /// </summary>
        internal static string ContextMenuEditMaterial {
            get {
                return ResourceManager.GetString("ContextMenuEditMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Selection.
        /// </summary>
        internal static string ContextMenuFreeze {
            get {
                return ResourceManager.GetString("ContextMenuFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show frozen in gray.
        /// </summary>
        internal static string ContextMenuFrozenInGray {
            get {
                return ResourceManager.GetString("ContextMenuFrozenInGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Selection.
        /// </summary>
        internal static string ContextMenuHide {
            get {
                return ResourceManager.GetString("ContextMenuHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit From Layer.
        /// </summary>
        internal static string ContextMenuInheritFromLayer {
            get {
                return ResourceManager.GetString("ContextMenuInheritFromLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All Objects Inherit From Layer.
        /// </summary>
        internal static string ContextMenuInheritFromLayerAll {
            get {
                return ResourceManager.GetString("ContextMenuInheritFromLayerAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Properties.
        /// </summary>
        internal static string ContextMenuLayerProperties {
            get {
                return ResourceManager.GetString("ContextMenuLayerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Container.
        /// </summary>
        internal static string ContextMenuNewContainer {
            get {
                return ResourceManager.GetString("ContextMenuNewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string ContextMenuNewGroup {
            get {
                return ResourceManager.GetString("ContextMenuNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Layer.
        /// </summary>
        internal static string ContextMenuNewLayer {
            get {
                return ResourceManager.GetString("ContextMenuNewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Properties.
        /// </summary>
        internal static string ContextMenuObjectProperties {
            get {
                return ResourceManager.GetString("ContextMenuObjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string ContextMenuRename {
            get {
                return ResourceManager.GetString("ContextMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render.
        /// </summary>
        internal static string ContextMenuRender {
            get {
                return ResourceManager.GetString("ContextMenuRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Shadows.
        /// </summary>
        internal static string ContextMenuRenderCastShadows {
            get {
                return ResourceManager.GetString("ContextMenuRenderCastShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Settings.
        /// </summary>
        internal static string ContextMenuRenderProperties {
            get {
                return ResourceManager.GetString("ContextMenuRenderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Shadows.
        /// </summary>
        internal static string ContextMenuRenderReceiveShadows {
            get {
                return ResourceManager.GetString("ContextMenuRenderReceiveShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible To Camera.
        /// </summary>
        internal static string ContextMenuRenderVisToCam {
            get {
                return ResourceManager.GetString("ContextMenuRenderVisToCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible To Reflections/Refractions.
        /// </summary>
        internal static string ContextMenuRenderVisToRefl {
            get {
                return ResourceManager.GetString("ContextMenuRenderVisToRefl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Childnodes.
        /// </summary>
        internal static string ContextMenuSelectChildnodes {
            get {
                return ResourceManager.GetString("ContextMenuSelectChildnodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Active Layer.
        /// </summary>
        internal static string ContextMenuSetActiveLayer {
            get {
                return ResourceManager.GetString("ContextMenuSetActiveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Material In Viewport.
        /// </summary>
        internal static string ContextMenuShowInVpt {
            get {
                return ResourceManager.GetString("ContextMenuShowInVpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze Selection.
        /// </summary>
        internal static string ContextMenuUnfreeze {
            get {
                return ResourceManager.GetString("ContextMenuUnfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        internal static string ContextMenuUngroup {
            get {
                return ResourceManager.GetString("ContextMenuUngroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide Selection.
        /// </summary>
        internal static string ContextMenuUnhide {
            get {
                return ResourceManager.GetString("ContextMenuUnhide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink.
        /// </summary>
        internal static string ContextMenuUnlink {
            get {
                return ResourceManager.GetString("ContextMenuUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "delete");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freeze {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "freeze");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freeze_button {
            get {
                return EmbeddedBitmapResources.Load("node_buttons", "freeze_button");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freeze_button_disabled {
            get {
                return EmbeddedBitmapResources.Load("node_buttons", "freeze_button_disabled");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hide {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "hide");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hide_button {
            get {
                return EmbeddedBitmapResources.Load("node_buttons", "hide_button");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hide_button_disabled {
            get {
                return EmbeddedBitmapResources.Load("node_buttons", "hide_button_disabled");
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer names must be unique (case-insensitive).
        /// </summary>
        internal static string InvalidLayerNameMessage {
            get {
                return ResourceManager.GetString("InvalidLayerNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid layer name.
        /// </summary>
        internal static string InvalidLayerNameTitle {
            get {
                return ResourceManager.GetString("InvalidLayerNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material names must be unique (case-insensitive).
        /// </summary>
        internal static string InvalidMaterialNameMessage {
            get {
                return ResourceManager.GetString("InvalidMaterialNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid material name.
        /// </summary>
        internal static string InvalidMaterialNameTitle {
            get {
                return ResourceManager.GetString("InvalidMaterialNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layer {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "layer");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newcontainer {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "newcontainer");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newgroup {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "newgroup");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newlayer {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "newlayer");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap properties {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "properties");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "rename");
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ungroup {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "ungroup");
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unlink {
            get {
                return EmbeddedBitmapResources.Load("contextmenu_icons", "unlink");
            }
        }
    }
}
